### ISSUE TITLE
Tell Sound + BGM every 2 seconds after getting a Tell

### ISSUE THREAD

**Issue by ghost** [reiichi001/Dalamud-FlashOnTellPlugin#1]
With this plugin enabled you get the Tell sound when tabbed out + the BGM sound every 2 seconds for like half a second after receiving a Tell, the BGM keeps turning on and off until you tab back into the game.
Even with all the "Play sound when inactive" function the game offers disabled.

The plugin is supposed to only flash my taskbar, not play the tell sound, and certainly not play the BGM every 2 seconds.

**Comment by reiichi001** [comment]
When the windows flashes, Windows considers that being in the forefront, which is why BGM that plays in the forefront is audible.

This is the exact same behavior as Dalamud's other "flash the game windows/taskbar icon" code, because that's what I copied from.

This is a limitation of the Windows API that is called. The plugin is operating as expected.
